In [177]:
import numpy as np

In [178]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [179]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Задание 1

In [180]:
mean_a = np.mean(a, 0)
mean_a

array([2. , 8.4])

# 

Задание 2

In [181]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [182]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])


In [190]:
a_centered_sp / (a_centered.shape[0]-1)

2.0

Задание 4

In [156]:
cov = np.cov(np.transpose(a))
cov

array([[1. , 2. ],
       [2. , 4.3]])

In [184]:
cov[0][1]

2.0